#!/usr/bin/env python3
"""Produce reversible crop alternatives from approved JPEGs, without recompression."""
from pathlib import Path
import hashlib,json,subprocess,html,re
from PIL import Image,ImageDraw
import numpy as np
ROOT=Path(__file__).resolve().parents[1];DOCS=ROOT/'docs';OUT=DOCS/'crop-review';OUT.mkdir(exist_ok=True)
version=json.loads((ROOT/'config.json').read_text())['media_version']
def versioned(name):return name+'?v='+version
media=json.loads((DOCS/'media-manifest.json').read_text());photos={p['id']:p for p in media['photos']}
# Bounds are on JPEG MCU boundaries and manually checked for composition.
choices=[
 ('dj-32-booth',32,(272,2592,4064,3048),'Recommended · DJ at work','Remove the ceiling and clock; keep both hands, the controller and the booth. This is the best balance of tighter framing and viewing comfort.'),
 ('dj-34-booth',34,(2080,960,4128,2752),'Recommended · DJ and equipment','Bring the DJ forward and reduce the empty room. Keep the environment around him; a headshot crop would expose more softness.'),
 ('dj-02-context',2,(3104,832,3840,2560),'Alternative · The raised-hand moment','A closer view with the gesture and console intact. The right speaker still carries visual weight; the portrait below removes more of it.'),
 ('dj-02-portrait',2,(3456,832,2176,2720),'Limited use · 4:5 portrait','The strongest subject emphasis, but existing softness becomes more noticeable. Suitable to consider at phone-feed size; not my choice for deep zoom or a large portrait.'),
 ('group-01-wide',1,(128,384,7936,3552),'Recommended · A tighter group frame','Trim surplus court while keeping every person and their feet. This is a gentler crop with much more of the original frame retained.')]
face={2:(.543,.338),32:(.537,.417),34:(.465,.355)}
rows=[];sections=[]
for slug,n,(x,y,w,h),title,note in choices:
 p=photos[n];source=ROOT/'artifacts/photos'/p['filename'] if p['full'].startswith('https://') else DOCS/p['full'];dest=OUT/(slug+'.jpg');full_href=p['full'] if p['full'].startswith('https://') else '../'+p['full']
 subprocess.run(['jpegtran','-copy','all','-optimize','-crop',f'{w}x{h}+{x}+{y}','-outfile',str(dest),str(source)],check=True)
 subprocess.run(['exiftool','-overwrite_original',f'-EXIF:ExifImageWidth={w}',f'-EXIF:ExifImageHeight={h}',f'-XMP-dc:Title=Photo {n:02}: {title}',f'-XMP-dc:Source={p["filename"]}',f'-XMP-dc:Description={note}','-XMP-xmp:CreatorTool=jpegtran lossless crop; no resizing or sharpening',str(dest)],check=True,capture_output=True)
 with Image.open(source) as original,Image.open(dest) as cropped:
  assert cropped.size==(w,h)
  assert cropped.info.get('icc_profile')==original.info.get('icc_profile')
  a=np.array(original.crop((x,y,x+w,y+h)));b=np.array(cropped)
  delta=np.abs(a[4:-4,4:-4].astype(np.int16)-b[4:-4,4:-4].astype(np.int16))
  assert delta.max()==0
  previews={}
  for edge in [960,2048]:
   im=cropped.copy();im.thumbnail((edge,edge*2 if edge==960 else edge));name=f'{slug}-{edge}.webp';im.save(OUT/name,'WEBP',quality=90,method=6,icc_profile=cropped.info.get('icc_profile'));previews[edge]=name
  detail=''
  if n in face:
   cx,cy=(round(original.width*face[n][0]),round(original.height*face[n][1]));box=(cx-256,cy-256,cx+256,cy+256)
   one=original.crop(box);two=cropped.crop((box[0]-x,box[1]-y,box[2]-x,box[3]-y))
   assert np.array_equal(np.array(one),np.array(two))
   for label,im in [('source',one),('crop',two)]:im.save(OUT/f'photo-{n:02}-{label}-detail.png',icc_profile=original.info.get('icc_profile'))
   detail=f'<details><summary>Inspect the same face detail before and after cropping</summary><p>These are matching 512 × 512 source-pixel sections with no enlargement. The crop preserves the detail of the freshly redeveloped RAW export. Swipe sideways to compare both panels at native size.</p><div class="detail-pair"><figure><img src="photo-{n:02}-source-detail.png" width="512" height="512" alt="Photo {n} source detail" loading="lazy"><figcaption>From the approved full frame</figcaption></figure><figure><img src="photo-{n:02}-crop-detail.png" width="512" height="512" alt="Photo {n} crop detail" loading="lazy"><figcaption>From the cropped JPEG</figcaption></figure></div></details>'
  retained=100*w*h/(original.width*original.height)
  row={'id':len(rows)+1,'source_photo':n,'filename':dest.name,'title':f'Photo {n:02} crop — {title.split(" · ")[-1]}','alt':f'Cropped view of tournament photo {n}: {note}','full':dest.name,'preview':previews[960],'display':previews[2048],'width':w,'height':h,'bytes':dest.stat().st_size,'sha256':hashlib.sha256(dest.read_bytes()).hexdigest(),'source_sha256':p['sha256'],'crop_xywh':[x,y,w,h],'pixels_retained_percent':round(retained,1),'pixel_check':{'interior_max_channel_difference':int(delta.max()),'excluded_decode_border_pixels':4},'recommendation':note}
  for key in ['full','preview','display']:row[key]=versioned(row[key])
  rows.append(row)
  overlay=f'left:{100*x/original.width:.5f}%;top:{100*y/original.height:.5f}%;width:{100*w/original.width:.5f}%;height:{100*h/original.height:.5f}%'
  sections.append(f'''<section id="{slug}"><p class="label">PHOTO {n:02} · {html.escape(title)}</p><h2>{html.escape(row['title'].split(' — ')[-1])}</h2><p class="explanation">{html.escape(note)}</p><div class="compare"><figure><div class="source-frame" style="max-width:{600*p['width']/p['height']:.2f}px;margin-inline:auto"><img src="../{p['display']}" width="{p['width']}" height="{p['height']}" alt="Approved full frame of photo {n} with suggested crop outlined" loading="lazy"><span class="crop-outline" style="{overlay}" aria-hidden="true"></span></div><figcaption>Full frame · proposed crop outlined <a href="{full_href}" target="_blank" rel="noopener">Open full frame ↗</a></figcaption></figure><figure><a class="photo-open" href="{dest.name}" data-pswp-width="{w}" data-pswp-height="{h}" aria-label="Zoom crop of photo {n}: {slug}"><img src="{previews[960]}" width="{w}" height="{h}" alt="{html.escape(row['alt'])}" loading="lazy"></a><figcaption>Proposed crop · tap to zoom <a href="{dest.name}" download>Download crop ↓</a></figcaption></figure></div><p class="spec">{w:,} × {h:,} pixels · {w*h/1e6:.1f} MP · {retained:.0f}% of the original pixels retained · no upscaling</p>{detail}</section>''')
(OUT/'crop-manifest.json').write_text(json.dumps(rows,indent=2)+'\n')
(OUT/'crop-data.js').write_text('window.GALLERY_DATA = '+json.dumps({'photos':rows})+';\n')
page='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Tournament crop review — framing and detail</title><link rel="stylesheet" href="../vendor/photoswipe.css"><link rel="stylesheet" href="../styles.css"><link rel="stylesheet" href="crop-review.css"></head><body><main><header class="review-header"><img src="../brand/tournament-emblem.jpg" width="68" height="68" alt="Tournament emblem"><a href="../">Back to the event gallery ↗</a></header><p class="label">COMPOSITION & DETAIL REVIEW</p><h1>Closer to the people.<br>Honest about the detail.</h1><p class="intro">The DJ photos benefit from less empty room and foreground. These five alternatives use the fresh RAW detail treatment and approved color edit and let you compare the framing, download the crop, and inspect it at full resolution.</p><aside><p><a href="../detail-review/"><strong>New: compare fresh RAW detail refinements for the DJ crops →</strong></a></p><strong>Framing recommendation</strong><p>Use the booth crops of #32 and #34, and the wider group crop. Keep #2’s portrait crop for smaller displays only. The DJ detail has been refined from the original RAWs. Some softness remains at native magnification; avoid excessive enlargement.</p><p>These JPEG crops preserve the new RAW export image data without another round of compression or upscaling. The main gallery and its ZIP downloads retain the approved full-frame photographs.</p></aside><nav class="review-nav" aria-label="Crop choices"><a href="#dj-32-booth">DJ #32</a><a href="#dj-34-booth">DJ #34</a><a href="#dj-02-context">DJ #2</a><a href="#dj-02-portrait">4:5 option</a><a href="#group-01-wide">Group</a></nav><div id="photo-wall">'''+''.join(sections)+'''</div><p class="end-note">Resolution is not a promise of sharpness. These choices are based on both composition and the visible source detail. Full-frame photos remain available in the event gallery.</p></main><script src="crop-data.js"></script><script type="module" src="../app.js"></script></body></html>'''
page=re.sub(r'((?:src|href)=")([^"#?]+\.(?:jpg|png|webp|js|css))(")',lambda m:m.group(0) if m.group(2).startswith('https://') else m.group(1)+versioned(m.group(2))+m.group(3),page)
(OUT/'index.html').write_text(page)
(OUT/'crop-review.css').write_text('''main{max-width:1280px;margin:auto;padding:24px 28px 60px}.review-header{display:flex;align-items:center;gap:18px;margin-bottom:45px}.review-header img{object-fit:contain;mix-blend-mode:multiply}.review-header a{color:var(--green);font-size:.85rem;text-decoration:underline}.label{color:var(--pink);font-weight:800;font-size:.75rem;letter-spacing:.06em;line-height:1.5}h1{font:400 clamp(2.6rem,5vw,4.5rem)/1.03 Impact,'Arial Narrow',sans-serif;margin:12px 0 25px}h2{font-size:2rem}.intro{font-size:1.1rem;max-width:820px;line-height:1.7}aside{background:#f3f3e7;border-left:5px solid var(--green);padding:22px 26px;margin:30px 0;max-width:920px;line-height:1.65}aside p{margin:10px 0 0}.review-nav{display:flex;gap:10px;flex-wrap:wrap;margin:28px 0}.review-nav a{border:1px solid var(--green);padding:12px 18px;font-size:.8rem;font-weight:bold}section{padding:32px 0 40px;border-top:1px solid var(--line);scroll-margin-top:15px}.explanation{line-height:1.7;max-width:900px}.compare{display:grid;grid-template-columns:1fr 1fr;gap:20px;align-items:start}figure{margin:0;min-width:0}.source-frame{position:relative}.source-frame img{display:block;width:100%;height:auto}.crop-outline{position:absolute;border:3px solid var(--pink);box-shadow:0 0 0 1px white inset;pointer-events:none}.compare .photo-open{background:#e8ece6}.compare .photo-open img{max-height:600px;object-fit:contain}.photo-open::after{opacity:1}figcaption{display:flex;justify-content:space-between;gap:12px;flex-wrap:wrap;padding:14px 0;font-size:.78rem;line-height:1.5}figcaption a{color:var(--pink);font-weight:bold;text-decoration:underline}.spec{font-size:.8rem;color:var(--muted);line-height:1.7}details{margin-top:22px;padding:16px;border:1px solid var(--line)}summary{cursor:pointer;font-size:.9rem;font-weight:bold;line-height:1.5}details p{font-size:.8rem;line-height:1.7;max-width:780px}.detail-pair{display:flex;gap:20px;overflow-x:auto;padding-bottom:12px}.detail-pair figure{flex:none;width:512px}.detail-pair img{width:512px;height:512px;max-width:none}.detail-pair figcaption{justify-content:flex-start}.end-note{color:var(--muted);font-size:.85rem;line-height:1.7}@media(max-width:680px){main{padding:18px 16px 40px}.review-header{margin-bottom:32px}.compare{grid-template-columns:1fr;gap:18px}aside{padding:18px}.review-nav a{padding:12px}h2{font-size:1.7rem}.intro{font-size:1rem}.spec{font-size:.75rem}.compare .photo-open img{max-height:none}}''')
size=sum(p.stat().st_size for p in DOCS.rglob('*') if p.is_file());assert size<1_000_000_000,size
print(json.dumps({'crops':len(rows),'site_bytes':size,'lossless_pixel_checks':'passed','output':str(OUT)},indent=2))
